---
:name: Patrick Dougall
:email: pdougall1@gmail.com
:web_address: http://patrickdougall.com
:github: https://github.com/pdougall1
:started_programming: '2012-01-02T00:00:00-05:00'
:basic_me:
- 'Always be learning!  A language, a style, depth in specific facet; learning is what keeps things exciting!'
- 'Always be teaching!  Grows you, them, and the community in wonderful ways :)'
- 'Object Oriented Programming! (even in the face of cool fun functional stuff, OOP is great in the 99% case)'
- "Build simple software.  Don't make people work hard to understand creative messes, but write simple, descrete units with a single purpose that can express that purpose in the way you write it."
- 'I love to mess around with fun side projects in my free time!  I have a dream of building a small community of light beings :)'
- 'Very "Right tool for the right job."'
- 'I like using languages, not just frameworks. POROs and POJOs are good things!'
:heroes:
- :Sandy Metz: 'Read POODR, done her training, love her thoughts on OO!'
  :Avdi Grim: 'Ruby Tapas, every week!  Wonderful mind around programming!'
  :Martin Fowler: 'Website is a much used reference.  Books are cannonical!'
:technologies:
- :Git: 'A nice git history is very important!'
  :Ruby on Rails: 'Great fascilitator, but the heart of my app it still the damain inside.'
  :Sinatra:
  :Postgres:
  :MySql:
  :Redis:
  :Continuous Integration: 'Travis CI, Codeship'
  :Lots of integrations: 'All over AWS, Google, private client APIs'
  :Ember: 'I am co-organizer of the Atlanta Ember Meetup'
  :React: 'A little sprincle here and there'
  :D3.js:
  :Go: 'Just in pet projects'
:jobs:
- :name: Big Nerd Ranch
  :web_address: http://www.bignerdranch.com/
  :start_date: '2014-09-01T00:00:00-04:00'
  :description_points:
  - BNR does consulting as well as teaching for major tech companies all over the world.
  - I adopted programming practices from (what I believe to be) some of the best programmers in the industry.
  :projects:
  - :name: Bookie
    :techs_used:
    - Ruby on Rails
    - PostgreSQL
    - Git
    - Travis CI
    - AWS SNS service
    - Google Calendar API
    - Google push notifications
    :description_points:
    - Receives and persists updates to a cache as the result of recieving Google Calendar Push notifications
    - Sends clients push notificaions about room changes through AWS SNS service
- :name: Look-Listen
  :web_address: http://look-listen.com/
  :start_date: '2013-08-12T00:00:00-04:00'
  :end_date: '2014-08-08T00:00:00-04:00'
  :description_points:
  - Lead developer on three Rails projects, two of which have Ember front ends.
  - Learn about an implement many technologies to solve real world problems.
  - Grew to rely on the use of basic language constructs (POROs and POJOs) to build systems from the ground up.
  :projects:
  - :name: GE online marketing tool
    :techs_used:
    - Ruby on Rails
    - PostgreSQL
    - Git
    - Ember.js
    - D3.js
    - AWS S3
    :description_points:
    - Illustrates the potential benefits to clients in real time
    - Uses databindings and D3.js for immediate results
    - Produces reports and emails them as PDFs
  - :name: Flywheel
    :techs_used:
    - Ruby on Rails
    - PostgreSQL
    - Git
    - Redis
    - MongoDB
    - Multiple APIs
    :description_points:
    - Aggrogates and stores data from
    - Transforms disperate sources and forms of data into a unifieng table
    - provides compiled reports of the data in a restful API
  - :name: Go Bike Go
    :techs_used:
    - Ruby on Rails
    - PostgreSQL
    - Git
    - jQuery
    :description_points:
    - Ticketing system for a series of bike shops to keep track of customers and the work required
- :name: SmartBIM
  :web_address: http://www.smartbim.com/
  :start_date: '2013-01-25T00:00:00-05:00'
  :end_date: '2013-08-06T00:00:00-04:00'
  :projects:
  - :techs_used:
    - Ruby on Rails
    - elasticsearch
    - PostgreSQL
    - Git
    - jQuery
    :description_points:
    - 3 Rails devs building and maintaining 3 Rails apps
    - Our main product was an online library used to find 3D models for Revit
    - This position introduced me to a large, complex system with multiple apps operating
      together
:personal_projects:
- :name: Friends Graph
  :techs_used:
  - Ruby on Rails API
  - PostgreSQL
  - Git
  - Redis
  - Sidekiq
  - Server Sent Events
  - LinkedIn API
  - Ember.js
  :description_points:
  - Imports the user's data including their connections
  - Graphs the connections on a D3.js force layout
- :name: Fun Schedular
  :techs_used:
  - Ruby on Rails
  - Ember.js
  - PostgreSQL
  - Git
  - Google Calendar API
  :description_points:
  - A tool to help my friends and I communicate about planning events better
- :name: Game of Life
  :techs_used:
  - Ember.js
  - D3.js
  :description_points:
  - Ember addon the provides a component one can include in their webpage
  - Uses D3.js to visualize the progression of Conway's Game of Life
- :name: Chipero
  :web_address: https://www.chipero.com/
  :start_date: '2012-10-31T00:00:00-04:00'
  :techs_used:
  - Ruby on Rails
  - Postgres
  - Git
  - jQuery
  - Google Maps API
  :description_points:
  - First Rails application I ever build (still in operation)
  - Connects truck mulching companies with people who need mulch
  - Has a strong mobile component
:education:
- :name: Georgia State University
  :degree: Masters of Neuroscience
  :gpa: 3.48/4.0
  :start_date: '2009-08-01T00:00:00-04:00'
  :end_date: '2012-01-01T00:00:00-05:00'
- :name: Georgia State University
  :degree: Bachelors of Science, Psychology
  :gpa: 3.6/4.0
  :accolades:
  - Magna Cum Laude
  - Honors Distinction
  :start_date: '2006-08-01T00:00:00-04:00'
  :end_date: '2009-05-01T00:00:00-04:00'

